import '@styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: {
      children: React.ReactNode
    }) => (
      <html lang='en'>
        <body>{children}</body>
      </html>
);

export default RootLayout;
